SITE_NAME(SNAP_BUILD_MACHINE)

SET(INSTALL_LIBS lib/snap-${SNAP_VERSION_FULL})

IF(SNAP_BUILD_MACHINE STREQUAL "pauly-laptop" AND NOT WIN32)
  INSTALL(
    FILES /usr/lib/libstdc++.so.6.0.9 
    DESTINATION ${INSTALL_LIBS}
    COMPONENT RUNTIME
    RENAME libstdc++.so.6)
  INSTALL(
    FILES /lib/libgcc_s.so.1
    DESTINATION ${INSTALL_LIBS}
    COMPONENT RUNTIME)
ENDIF(SNAP_BUILD_MACHINE STREQUAL "pauly-laptop" AND NOT WIN32)
